version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    networks:
      - qa_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend:8080
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    depends_on:
      - backend
    networks:
      - qa_network

networks:
  qa_network:
    driver: bridge
