apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-backend
  labels:
    app: qa-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-backend
  template:
    metadata:
      labels:
        app: qa-backend
    spec:
      containers:
      - name: backend
        image: jatinyadav02022003/ai-test-pilot-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: env-config
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: env-config
        configMap:
          name: qa-env-config
---
apiVersion: v1
kind: Service
metadata:
  name: qa-backend-service
spec:
  selector:
    app: qa-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
